export const FETCH_TODO_LIST_START = "FETCH_TODO_LIST_START";
export const FETCH_TODO_LIST_SUCCESS = "FETCH_TODO_LIST_SUCCESS";
export const FETCH_TODO_LIST_FAIL = "FETCH_TODO_LIST_FAIL";

export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const EDIT_TODO_TITLE = "EDIT_TODO_TITLE";
export const SET_TODO_COMPLETED_STATUS = "SET_TODO_COMPLETED_STATUS";
