export const FETCH_TODO_LIST_START = "FETCH_TODO_LIST_START";
export const FETCH_TODO_LIST_SUCCESS = "FETCH_TODO_LIST_SUCCESS";
export const FETCH_TODO_LIST_FAIL = "FETCH_TODO_LIST_FAIL";

export const ADD_OR_EDIT_TODO_START = "ADD_OR_EDIT_TODO_START";
export const ADD_OR_EDIT_TODO_SUCCESS = "ADD_OR_EDIT_TODO_SUCCESS";
export const ADD_OR_EDIT_TODO_FAIL = "ADD_OR_EDIT_TODO_FAIL";

export const REMOVE_TODO_START = "REMOVE_TODO_START";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAIL = "REMOVE_TODO_FAIL";

export const EDIT_TODO_TITLE = "EDIT_TODO_TITLE";
export const SET_TODO_COMPLETED_STATUS = "SET_TODO_COMPLETED_STATUS";
